apiVersion: v1
kind: Service
metadata:
  name: datsec-service
spec:
  selector:
    app: datsec-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datsec-webapp
spec:
  selector:
    matchLabels:
      app: datsec-webapp
  replicas: 5
  template:
    metadata:
      labels:
        app: datsec-webapp
    spec:
      containers:
      - name: datsec-webapp
        image: sushanthsk/datsec-webapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
